name: Build and Publish

on:
  push:
    branches: [master]
  workflow_dispatch:


jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '8.0.x'
    
    - name: Publish Executable
      run: dotnet publish XBatteryStatus/XBatteryStatus.csproj -p:PublishProfile=XBatteryStatus\Properties\PublishProfiles\FolderProfile.pubxml
    
    - name: Publish Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: published-app
        path: XBatteryStatus/bin/Release/publish/XBatteryStatus.exe

    - name: Build Installer
      uses: caphyon/advinst-github-action@main
      with:
        advinst-version: '23.1'
        advinst-license: ${{ secrets.ADVINST_LICENSE_KEY }}
        advinst-enable-automation: 'true'
        aip-path: ${{ github.workspace }}\Installer/XBatteryStatus.aip
        aip-build-name: x64_Release
        aip-package-name: XBatteryStatus.msi
        aip-output-dir:  ${{ github.workspace }}\Installer\setup
        
    - name: Publish Installer Artifacts
      uses: actions/upload-artifact@main
      with:
        name: setup
        path: ${{ github.workspace }}\Installer\setup\XBatteryStatus.msi
