name: Build and Publish

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore XBatteryStatus/XBatteryStatus.csproj
    
    - name: Build
      run: dotnet build XBatteryStatus/XBatteryStatus.csproj --configuration Release --no-restore
    
    - name: Publish
      run: dotnet publish XBatteryStatus/XBatteryStatus.csproj --configuration Release --no-build -p:PublishProfile=FolderProfile.pubxml
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: published-app
        path: XBatteryStatus/bin/Release/net8.0/publish/